### ISSUE TITLE
Chyba po zmene na strankach

### ISSUE THREAD

**Issue by jose1711** [wombat01/plugin.video.xtv.cz#2]
```
2020-07-16 22:28:57.451 T:140294427334400   DEBUG: [XTV.cz] fetchUrl https://xtv.cz/porady
2020-07-16 22:28:57.730 T:140294427334400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'find'
                                            Traceback (most recent call last):
                                              File "/home/jose/.kodi/addons/plugin.video.xtv.cz/addon.py", line 194, in <module>
                                                listShows()
                                              File "/home/jose/.kodi/addons/plugin.video.xtv.cz/addon.py", line 58, in listShows
                                                thumb = detail.find('img', {'class': 'porad-logo'})['src']
                                            AttributeError: 'NoneType' object has no attribute 'find'
                                            -->End of Python script error report<--
```

**Comment by wombat01** [comment]
Opraveno v 1.2.0
